# Generated by Django 5.2.1 on 2025-07-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioatencion',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
