# Generated by Django 5.2.1 on 2025-07-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_horarioatencion_activo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together=set(),
        ),
    ]
